grafana

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,130 +1,130 @@
-name: CI Pipeline
+# name: CI Pipeline
 
-on: push
+# on: push
 
-jobs:
-  Continous-Integration:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+# jobs:
+#   Continous-Integration:
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Checkout code
+#         uses: actions/checkout@v3
 
-      - name: Setup Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.10'
+#       - name: Setup Python
+#         uses: actions/setup-python@v2
+#         with:
+#           python-version: '3.10'
 
-      - name: Cache pip dependencies
-        uses: actions/cache@v3
-        with:
-          path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
-          restore-keys: |
-            ${{ runner.os }}-pip-
+#       - name: Cache pip dependencies
+#         uses: actions/cache@v3
+#         with:
+#           path: ~/.cache/pip
+#           key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
+#           restore-keys: |
+#             ${{ runner.os }}-pip-
 
-      - name: Install dependencies
-        run: |
-          pip install --no-cache-dir -r requirements.txt
-          pip install dvc[s3]   # or your remote type
+#       - name: Install dependencies
+#         run: |
+#           pip install --no-cache-dir -r requirements.txt
+#           pip install dvc[s3]   # or your remote type
 
-      - name: Pull DVC data
-        env:
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          AWS_DEFAULT_REGION: us-east-1
-        run: dvc pull --force
+#       - name: Pull DVC data
+#         env:
+#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#           AWS_DEFAULT_REGION: us-east-1
+#         run: dvc pull --force
 
-      - name: Verify DVC data
-        run: ls -R ./data ./models
+#       - name: Verify DVC data
+#         run: ls -R ./data ./models
 
-      # - name: Generate dummy inference input
-      #   run: |
-      #    echo '{"text": "ew david" , "character": "david"}' > data/inference_input.json
+#       # - name: Generate dummy inference input
+#       #   run: |
+#       #    echo '{"text": "ew david" , "character": "david"}' > data/inference_input.json
 
-      # - name: Run DVC pipeline
-      #   env:
-      #     CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
-      #   run: dvc repro
+#       # - name: Run DVC pipeline
+#       #   env:
+#       #     CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
+#       #   run: dvc repro
 
-      # - name: Run model tests
-      #   env:
-      #     CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
-      #   run: |
-      #     python -m unittest tests/test_model.py
+#       # - name: Run model tests
+#       #   env:
+#       #     CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
+#       #   run: |
+#       #     python -m unittest tests/test_model.py
 
-      # - name: Promote model to production
-      #   if: success()
-      #   env:
-      #     CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
-      #   run: python scripts/promote_model.py
+#       # - name: Promote model to production
+#       #   if: success()
+#       #   env:
+#       #     CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
+#       #   run: python scripts/promote_model.py
 
-      # - name: Run Flask app tests
-      #   if: success()
-      #   env:
-      #     CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
-      #   run: python -m unittest tests/test_app.py
+#       # - name: Run Flask app tests
+#       #   if: success()
+#       #   env:
+#       #     CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
+#       #   run: python -m unittest tests/test_app.py
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+#       - name: Configure AWS credentials
+#         uses: aws-actions/configure-aws-credentials@v1
+#         with:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#           aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
 
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
+#       - name: Login to Amazon ECR
+#         id: login-ecr
+#         uses: aws-actions/amazon-ecr-login@v1
 
-      - name: Clean up Docker
-        run: |
-          docker system prune -af || true
+#       - name: Clean up Docker
+#         run: |
+#           docker system prune -af || true
 
-      - name: Set up Docker
-        uses: docker/setup-buildx-action@v3
+#       - name: Set up Docker
+#         uses: docker/setup-buildx-action@v3
 
-      - name: Build, tag, and push image to Amazon ECR
-        id: build-image
-        env:
-          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: ${{ secrets.ECR_REPO }}
-          IMAGE_TAG: latest
-        run: |
-           # Build Docker image
-            docker build --pull -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+#       - name: Build, tag, and push image to Amazon ECR
+#         id: build-image
+#         env:
+#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+#           ECR_REPOSITORY: ${{ secrets.ECR_REPO }}
+#           IMAGE_TAG: latest
+#         run: |
+#            # Build Docker image
+#             docker build --pull -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
 
-            # Push Docker image to ECR
-            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+#             # Push Docker image to ECR
+#             docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
-            # Output image info
-            echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
+#             # Output image info
+#             echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
 
 
-  Continuous-Deployment:
-    needs: Continous-Integration
-    runs-on: self-hosted
+#   Continuous-Deployment:
+#     needs: Continous-Integration
+#     runs-on: self-hosted
 
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v3
 
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
+#       - name: Configure AWS credentials
+#         uses: aws-actions/configure-aws-credentials@v1
+#         with:
+#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#           aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
 
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v1
+#       - name: Login to Amazon ECR
+#         id: login-ecr
+#         uses: aws-actions/amazon-ecr-login@v1
 
-      - name: Run Docker Image to serve users
-        run: |
-          docker rm -f myapp || true
-          docker run -d --name myapp  --restart unless-stopped \
-            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
-            -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
-            -e AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}" \
-            -e CAPSTONE_TEST="${{ secrets.CAPSTONE_TEST }}" \
-            -p 5002:5001 \
-            "${{ steps.login-ecr.outputs.registry }}"/"${{ secrets.ECR_REPO }}":latest
+#       - name: Run Docker Image to serve users
+#         run: |
+#           docker rm -f myapp || true
+#           docker run -d --name myapp  --restart unless-stopped \
+#             -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
+#             -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
+#             -e AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}" \
+#             -e CAPSTONE_TEST="${{ secrets.CAPSTONE_TEST }}" \
+#             -p 5002:5001 \
+#             "${{ steps.login-ecr.outputs.registry }}"/"${{ secrets.ECR_REPO }}":latest
